import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'passport_service.dart';

class PhotojournalExportService {
  static Future<void> exportJourneyPdf() async {
    final pdf = pw.Document();
    final stamps = await PassportService.getStamps();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header Banner
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(20),
                decoration: const pw.BoxDecoration(
                  color: PdfColor.fromInt(0xFF342116),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'HERITAGE LK — MY JOURNEY',
                      style: const pw.TextStyle(
                        color: PdfColor.fromInt(0xFFF4A261),
                        fontSize: 22,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      'Official Explorer Certificate & Cultural Travelogue',
                      style: const pw.TextStyle(
                        color: PdfColor.fromInt(0xFFFEFAE0),
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Summary Stats
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Total Sites Explored: ${stamps.length}', style: const pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.Text('Passport Tier: ${PassportService.getTierName(stamps.length)}', style: const pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                ],
              ),
              pw.Divider(thickness: 1, color: PdfColors.grey300),
              pw.SizedBox(height: 14),

              pw.Text(
                'Recorded Expeditions',
                style: const pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColor.fromInt(0xFF342116)),
              ),
              pw.SizedBox(height: 10),

              // Entries List
              ...stamps.map(
                (stamp) => pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 12),
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey400),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(stamp.siteName, style: const pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 13)),
                          pw.Text('Verified via: ${stamp.method.toUpperCase()} • ${stamp.category ?? "Heritage Site"}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                        ],
                      ),
                      pw.Text(
                        '${stamp.earnedAt.year}-${stamp.earnedAt.month.toString().padLeft(2, '0')}-${stamp.earnedAt.day.toString().padLeft(2, '0')}',
                        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
                      ),
                    ],
                  ),
                ),
              ),

              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text(
                  'Generated by HeritageLK — Guardian of Sri Lanka Heritage',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'HeritageLK_Journey_Passport.pdf',
    );
  }
}
