import 'package:flutter/material.dart';
import '../theme/heritage_colors.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 16, 24, 32), children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_round(Icons.arrow_back, () => Navigator.of(context).pushReplacementNamed('/profile')), const Text('Settings', style: TextStyle(color: HeritageColors.cream, fontFamily: 'Playfair Display', fontSize: 24, fontWeight: FontWeight.bold)), _round(Icons.info_outline, () {})]), const SizedBox(height: 32), const Text('HeritageLK', style: TextStyle(color: HeritageColors.orange, fontSize: 18, fontWeight: FontWeight.bold)), const Text('EDIT PROFILE', style: TextStyle(color: Color(0xCCF4A261), fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1)), const SizedBox(height: 24), Row(children: [ClipOval(child: Image.network('https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=200&auto=format&fit=crop', width: 56, height: 56, fit: BoxFit.cover, errorBuilder: (_, __, ___) => const CircleAvatar(backgroundColor: HeritageColors.brown))), const SizedBox(width: 16), const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Explorer', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)), Text('Curator Level 4', style: TextStyle(color: Color(0xCCF4A261), fontSize: 14))])]), const SizedBox(height: 40), _section('ACCOUNT', [('Personal Information', Icons.person_outline), ('Security', Icons.lock_outline)]), const SizedBox(height: 32), _section('PREFERENCES & PRIVACY', [('Notifications', Icons.notifications_none), ('Privacy & Data', Icons.shield_outlined)]), const SizedBox(height: 32), _section('SUPPORT', [('Help & Support', Icons.help_outline), ('About HeritageLK', Icons.info_outline)]), const SizedBox(height: 32), InkWell(onTap: () => Navigator.of(context).pushReplacementNamed('/login'), child: Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: const Color(0x1AE76F51), border: Border.all(color: const Color(0x33E76F51)), borderRadius: BorderRadius.circular(16)), child: const Row(children: [Icon(Icons.logout, color: Color(0xFFE76F51)), SizedBox(width: 16), Text('Log Out', style: TextStyle(color: Color(0xFFE76F51), fontWeight: FontWeight.bold))]))) ]));
  Widget _section(String title, List<(String, IconData)> items) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(color: Color(0x80F4A261), fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 2)), const SizedBox(height: 12), ...items.map((item) => Container(margin: const EdgeInsets.only(bottom: 8), padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: Colors.white.withOpacity(0.05), border: Border.all(color: Colors.white.withOpacity(0.05)), borderRadius: BorderRadius.circular(16)), child: Row(children: [Icon(item.$2, color: HeritageColors.orange, size: 20), const SizedBox(width: 16), Expanded(child: Text(item.$1, style: const TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.w500))), const Icon(Icons.chevron_right, color: Color(0x66FFFFFF), size: 18)]))) ]);
  Widget _round(IconData icon, VoidCallback action) => InkWell(onTap: action, borderRadius: BorderRadius.circular(24), child: Container(width: 40, height: 40, decoration: BoxDecoration(color: Colors.white.withOpacity(0.10), border: Border.all(color: Colors.white.withOpacity(0.10)), shape: BoxShape.circle), child: Icon(icon, color: HeritageColors.orange, size: 20)));
}
